# 1. Scrape the details of most viewed videos on YouTube from Wikipedia.

Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
* A) Rank
* B) Name
* C) Artist
* D) Upload date
* E) Views

In [1]:
# import necessary libraries at once

import pandas as pd
import selenium
import time
from bs4 import BeautifulSoup 
from selenium import webdriver
from selenium.webdriver.common.by import By

from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
import requests
import re
from selenium.webdriver.support.ui import WebDriverWait
import warnings
warnings.filterwarnings('ignore')

In [9]:
driver=webdriver.Chrome('chromedriver.exe')

# Getting the webpage of url 

url=('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
driver.get(url)

In [10]:
# Creating empty list for storing data after scraping

Rank = []
Name = []
Artist = []
UploadDate = []
Views = []


# Scraping Rank of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
    
    
#scrapping rank
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]"):
        Name.append(i.text)
except NoSuchElementException:
    Name.append("_")
    
    
#scrapping Artist
try:
    for i in driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr/td[3]'):
        Artist.append(i.text)
except NoSuchElementException:
    Artist.append("_")
    
    
#Scrapping Date
try:
    for i in driver.find_elements(By.XPATH,' //table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[5]'):
        UploadDate.append(i.text)
except NoSuchElementException:
    UploadDate.append('-')
# Scraping Views of videos


try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]"):
        Views.append(i.text)
except NoSuchElementException:
    Views.append("_")

In [13]:
# Creating DataFrame from scraped data
wikipedia = pd.DataFrame({})
wikipedia['Rank']=Rank
wikipedia['Name']=Name
wikipedia['Artist']=Artist
wikipedia['Upload Date']=UploadDate
wikipedia['Views']=Views

In [14]:
wikipedia

,Rank,Name,Artist,Upload Date,Views
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",11.05
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.93
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.40
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.77
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.59
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.54
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,"March 6, 2014",4.77
7,8.,"""Uptown Funk""[22]",Mark Ronson,"November 19, 2014",4.65
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,"February 27, 2018",4.60
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,"January 31, 2012",4.50
10,11.,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.50
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.24
12,13.,"""Dame Tu Cosita""[31]",El Chombo,"April 5, 2018",4.00
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.74
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.63
15,16.,"""Counting Stars""[34]",OneRepublic,"May 31, 2013",3.62
16,17.,"""Sorry""[35]",Justin Bieber,"October 22, 2015",3.57
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.48
18,19.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.45
19,20.,"""Dark Horse""[38]",Katy Perry,"February 20, 2014",3.32
20,21.,"""Girls Like You""[39]",Maroon 5,"May 31, 2018",3.32
21,22.,"""Faded""[40]",Alan Walker,"December 3, 2015",3.32
22,23.,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.31
23,24.,"""Let Her Go""[42]",Passenger,"July 25, 2012",3.27
24,25.,"""Bailando""[43]",Enrique Iglesias,"April 11, 2014",3.25
25,26.,"""Lean On""[44]",Major Lazer,"March 22, 2015",3.24
26,27.,"""Perfect""[45]",Ed Sheeran,"November 9, 2017",3.22
27,28.,"""Waka Waka (This Time for Africa)""[46]",Shakira,"June 4, 2010",3.21
28,29.,"""Shake It Off""[47]",Taylor Swift,"August 18, 2014",3.19
29,30.,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.11

In [15]:
driver.close()

# 2. Scrape the details team India’s international fixtures from bcci.tv.

Url = https://www.bcci.tv/.
You need to find following details:
* A) Match title (I.e. 1st ODI)
* B) Series
* C) Place
* D) Date
* E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [103]:
driver=webdriver.Chrome('chromedriver.exe')

# Getting the webpage of mentioned url 
url=('https://www.bcci.tv/')
driver.get(url)

In [104]:
#clickin on International tab
International = driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a') # click button
International.click()

In [105]:
#Creating Empty List
Name=[]
Series=[]
Place=[]
Date=[]
Time=[]
#Scrapping Name
try:
    for i in driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]'):
        Name.append(i.text.replace('-',""))
except NoSuchElementException:
    Name.append('-')
#Scrapping Series
try:
    
    for i in driver.find_elements(By.XPATH,'//span[@class="ng-binding"]'):
        Series.append(i.text)
except NoSuchElementException:
    Series.append('-')
#scrapping Place
try:
    for i in driver.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]'):
        Place.append(i.text)
except NoSuchElementException:
    Place.append('-')
#Scrapping Date
try:
    for i in driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]'):
        Date.append(i.text)
except NoSuchElementException:
    Date.append('-')
#Scrapping Time
try:
    for i in driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]'):
        Time.append(i.text.replace('IST',""))
except NoSuchElementException:
    Time.append('-')

In [107]:
# Create Dataframe

Fixtures=pd.DataFrame({})
Fixtures['Title']=Series
Fixtures['Name']=Name
Fixtures['Place']=Place
Fixtures['Date']=Date
Fixtures['Time']=Time
Fixtures

,Title,Name,Place,Date,Time
0,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,1st ODI,"Harare Sports Club,",18 AUG 2022,12:45 PM
1,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,2nd ODI,"Harare Sports Club,",20 AUG 2022,12:45 PM
2,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,3rd ODI,"Harare Sports Club,",22 AUG 2022,12:45 PM
3,ASIA CUP 2022,1st T20I,"Dubai International Cricket Stadium,",28 AUG 2022,7:30 PM
4,ASIA CUP 2022,2nd T20I,"Dubai International Cricket Stadium,",31 AUG 2022,7:30 PM

In [30]:
driver.close()

# 3. Scrape the details of selenium exception from guru99.com.

Url = https://www.guru99.com/
You need to find following details:
* A) Name
* B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [2]:
driver=webdriver.Chrome('chromedriver.exe')

# get webpage
driver.get("https://www.guru99.com/")
driver.maximize_window()

In [3]:
# Click Selenium Button
Selenium = driver.find_element(By.XPATH,'//div[@class = "wp-block-kadence-column inner-column-2 kadence-column_f38d98-3a"]') # click button
try:
    Selenium.click()
except ElementNotInteractableException:#handling element not clickable exception
    driver.get(Selenium.get_attribute('href'))
time.sleep(3)

In [4]:
# Click selenium exception handling  Button
exception_handling = driver.find_element(By.XPATH,"//a[@title='Selenium Exception Handling (Common Exceptions List)']")
try:
    exception_handling.click()
except ElementNotInteractableException:  #if the above code doesn't work/is not clickable then, the below code will handle it
    driver.get(exception_handling.get_attribute('href'))

In [5]:
name=[]
desc=[]
#Scrapping Name
for i in driver.find_elements(By.XPATH,'//table[@class="table table-striped"]/tbody/tr/td[1]'):
    name.append(i.text)
for i in driver.find_elements(By.XPATH,'//table[@class="table table-striped"]/tbody/tr/td[2]'):
    desc.append(i.text)

In [6]:
Selenium_Exception=pd.DataFrame()
Selenium_Exception['Exception name']=name
Selenium_Exception['Description']=desc
Selenium_Exception

,Exception name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [7]:
driver.close()

# 4. Scrape the details of State-wise GDP of India from statisticstime.com.

Url = http://statisticstimes.com/
You have to find following details:
* A) Rank
* B) State
* C) GSDP(18-19)
* D) GSDP(17-18)
* E) Share(2017)
* F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [36]:
driver=webdriver.Chrome('chromedriver.exe')
driver.maximize_window()
driver.get('https://www.statisticstimes.com')
time.sleep(3)

In [37]:
driver.find_element(By.XPATH,'/html/body/div[1]/div/a').click()

In [38]:
 #Clicking on Economy button
driver.find_element(By.XPATH,"//div[@class='navbar']/div[2]/button").click()

In [39]:
#Clicking on India
driver.find_element(By.XPATH,"//div[@class='dropdown-content']/a[3]").click()

In [40]:
# Clicking on GDP of Indian Economy
GDP = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()
time.sleep(3)

In [41]:
# Creating empty list
Rank = []
State = []
GSDP2 = []
Share = []
GDPbillion = []
# Scraping Rank
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
# Scraping State
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException:
    State.append("_")
# Scraping GSDP at current price (18-19)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException:
    GSDP2.append("_")
# Scraping Share (18-19)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException:
    Share.append("_")
# Scraping GDP $ billion
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDPbillion.append(i.text)
except NoSuchElementException:
    GDPbillion.append("_")

In [42]:
INDIA=pd.DataFrame()
INDIA['RANK']=Rank
INDIA['STATE']=State
INDIA['GSDP2']=GSDP2
INDIA['SHARE']=Share
INDIA['GDPbillion']=GDPbillion
INDIA

   RANK                      STATE      GSDP2   SHARE GDPbillion
0     1                Maharashtra  2,632,792  13.94%    399.921
1     2                 Tamil Nadu  1,630,208   8.63%    247.629
2     3              Uttar Pradesh  1,584,764   8.39%    240.726
3     4                    Gujarat  1,502,899   7.96%    228.290
4     5                  Karnataka  1,493,127   7.91%    226.806
..  ...                        ...        ...     ...        ...
61   29                     Sikkim     25,141   0.15%     17,060
62   30                   Nagaland     24,534   0.15%          -
63   31          Arunachal Pradesh     22,488   0.13%          -
64   32                    Mizoram     20,947   0.13%     17,797
65   33  Andaman & Nicobar Islands          -       -          -

[66 rows x 5 columns]

GSDP 17-18 IS NOT AVAILABLE IN WEBSITE.

# 5. Scrape the details of trending repositories on Github.com.

Url = https://github.com/
You have to find the following details:
* A) Repository title
* B) Repository description
* C) Contributors count
* D) Language used

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [51]:
driver=webdriver.Chrome('chromedriver.exe')
url=('https://github.com/')
driver.get(url)

In [52]:
# Click on explore

explore = driver.find_element(By.XPATH,'//li[@class = "mr-0 mr-lg-3 position-relative flex-wrap flex-justify-between flex-items-center border-bottom border-lg-bottom-0 d-block d-lg-flex flex-lg-nowrap flex-lg-items-center"][4]')
try:
    explore.click()
    time.sleep(5)
except ElementNotInteractableException:
    driver.get(explore.get_attribute('href'))

In [53]:
# Click on Trending

trending = driver.find_element(By.XPATH,'//*[@href="/trending"]')
try:
    driver.get(trending.get_attribute('href'))
except ElementNotInteractableException:
    driver.get(trending.get_attribute('href'))

In [54]:
#Creating empty list:
URLs = []
repository_title = []
Description = []
Contributors = []
Language = []
lang = []

#Fetching urls for each repository
repository = driver.find_elements(By.XPATH,"//h1[@class = 'h3 lh-condensed']//a")
for i in repository:
    URLs.append(i.get_attribute("href"))

In [55]:
# Scraping Repository Title data
title = driver.find_elements(By.XPATH,"//h1[@class = 'h3 lh-condensed']")
for i in title:
    repository_title.append(i.text)

In [56]:
# Scraping data from all repository page
for i in URLs:
    driver.get(i)
    time.sleep(2)
    
        # Scraping Repository Description data
    try:
        desc = driver.find_element(By.XPATH,"//p[@class='f4 my-3']")
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')
        
        
    # Scraping Contributors Count data
    try:
        contributor = driver.find_element(By.XPATH,"//*[contains(text(),'    Contributors ')]")
        Contributors.append(contributor.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')
        
        
     # Scraping Languages used data
    lang=[]
    try:
        for i in driver.find_elements(By.XPATH,'//span[@class="color-fg-default text-bold mr-1"]'):
            lang.append(i.text)
        Language.append(lang)
    except NoSuchElementException:
        lang.append('-')

In [58]:
print(len(repository_title),len(Description),len(Contributors),len(Language))

25 25 25 25

In [57]:
#Data Frame

Github=pd.DataFrame({})
Github['Repository title'] = repository_title
Github['Repository description'] = Description
Github['Contributors count'] = Contributors
Github['Language used'] = Language
Github

,Repository title,Repository description,Contributors count,Language used
0,toeverything / AFFiNE,There can be more than Notion and Miro. Affine...,15,"[TypeScript, JavaScript, CSS, SCSS, HTML, Shell]"
1,utmapp / UTM,Virtual machines for iOS and macOS,40,"[Swift, Objective-C, Python, C, Shell]"
2,NVIDIAGameWorks / kaolin-wisp,NVIDIA Kaolin Wisp is a PyTorch library powere...,4,"[Python, Groovy, Cuda, C++, Dockerfile]"
3,microsoft / terminal,The new Windows Terminal and the original Wind...,336,"[C++, C#, C, PowerShell, Batchfile, HLSL]"
4,jina-ai / discoart,Create Disco Diffusion artworks in one line,5,"[Python, Jupyter Notebook, Shell, Dockerfile]"
5,martinshkreli / models,stock market models - have fun,-,[]
6,facebookresearch / ParlAI,A framework for training and evaluating AI mod...,182,"[Python, HTML, JavaScript, CSS, Shell, Cuda]"
7,KalleHallden / exer_log,-,4,"[Dart, HTML, Other]"
8,juliocesarfort / public-pentesting-reports,Curated list of public penetration test report...,33,"[CSS, C, JavaScript, Makefile, Shell]"
9,EbookFoundation / free-programming-books,📚 Freely available programming books,"1,988",[]
10,moyix / fauxpilot,FauxPilot - an open-source GitHub Copilot server,3,"[Python, Shell, Dockerfile]"
11,josejesusguzman / acordeon-az500-innoovaccion,-,-,[]
12,adiwajshing / Baileys,Lightweight full-featured WhatsApp Web + Multi...,86,"[JavaScript, TypeScript]"
13,qmk / qmk_firmware,Open-source keyboard firmware for Atmel AVR an...,"1,747","[C, Makefile, C++, Python, Shell, Roff]"
14,valinet / ExplorerPatcher,This project aims to enhance the working envir...,6,[C]
15,PKUFlyingPig / cs-self-learning,计算机自学指南,43,[HTML]
16,lucidrains / imagen-pytorch,"Implementation of Imagen, Google's Text-to-Ima...",11,[Python]
17,Womsxd / AutoMihoyoBBS,米游社自动签到，支持：崩坏二、崩坏三、原神、未定事件簿，米游币自动获取,16,"[Python, Dockerfile]"
18,getify / You-Dont-Know-JS,A book series on JavaScript. @YDKJS on twitter.,177,[]
19,coolsnowwolf / lede,Lean's OpenWrt source,301,"[C, Makefile, Shell, Roff, Perl, M4, Other]"
20,google-research / multinerf,"A Code Release for Mip-NeRF 360, Ref-NeRF, and...",2,"[Python, Jupyter Notebook, Shell]"
21,termux / termux-app,Termux - a terminal emulator application for A...,61,"[Java, C++, Other]"
22,godotengine / godot,Godot Engine – Multi-platform 2D and 3D game e...,"1,729","[C++, C#, C, GLSL, Java, Python, Other]"
23,rust-lang / rust-analyzer,A Rust compiler front-end for IDEs,585,"[Rust, HTML, TypeScript]"
24,ventoy / Ventoy,A new bootable USB solution.,74,"[C, Shell, HTML, C++, CSS, Makefile, Other]"

In [59]:
driver.close()

# 6. Scrape the details of top 100 songs on billiboard.com.

Url = https:/www.billboard.com/
You have to find the following details:
* A) Song name
* B) Artist name
* C) Last week rank
* D) Peak rank
* E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [60]:
driver=webdriver.Chrome('chromedriver.exe')
driver.maximize_window()
# Getting the webpage of mentioned url 
driver.get('https://www.billboard.com/')

In [62]:
#Clicking on charts
charts=driver.find_element(By.XPATH,'//*[@id="main-wrapper"]/header/div[2]/div/nav/ul/li[1]/a').click()

In [63]:
# Creating empty lists
Song_Name = []
Artist_Name = []
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

In [64]:
# Scraping name
for i in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]'):
    Song_Name.append(i.text)
len(Song_Name)

100

In [65]:
#Scrappin Artist name 1 st one
Artist_Name.append(driver.find_element(By.XPATH,"//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet']").text)
#Remainig Artist Name
artistTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only']")
Artist_Name.extend([i.text for i in artistTag])
#Scapping Rank
rank=[]
rankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet']")
rank.extend([i.text for i in rankTag[:3]])
#Remaining RAnk
Rank=[]
RankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']")
Rank.extend([i.text for i in RankTag])

In [69]:
# removing ''
for i in Rank:
    if i=='':
        Rank.remove(i)

In [70]:
# slicing as per requirement
lastweekpos=Rank[0::3]
lastweekpos.insert(0,rank[0])
peakPos=Rank[1::3]
peakPos.insert(0,rank[1])
weeksonBoard=Rank[2::3]
weeksonBoard.insert(0,rank[2])

In [71]:
#check length of all
len(Song_Name),len(Artist_Name),len(lastweekpos),len(peakPos),len(weeksonBoard)

(100, 100, 111, 111, 111)

In [72]:
# Create Dataframe
df=pd.DataFrame()
df['SongName']=Song_Name[0:100]
df['ArtistName']=Artist_Name
df['Last Week']=lastweekpos[0:100]
df["PeekPosition"]=peakPos[0:100]
df['Weeks On board']=weeksonBoard[0:100]
df

,SongName,ArtistName,Last Week,PeekPosition,Weeks On board
0,About Damn Time\nLizzo\n1\n1\n15,Lizzo,1,1,15
1,As It Was\nHarry Styles\n2\n1\n17,Harry Styles,2,1,17
2,Running Up That Hill (A Deal With God)\nKate B...,Kate Bush,3,3,29
3,First Class\nJack Harlow\n4\n1\n16,Jack Harlow,4,1,16
4,Wait For U\nFuture Featuring Drake & Tems\n5\n...,Future Featuring Drake & Tems,5,1,13
...,...,...,...,...,...
95,Te Felicito\nShakira & Rauw Alejandro\n95\n67\n8,Shakira & Rauw Alejandro,91,16,12
96,Are You Entertained\nRuss & Ed Sheeran\n-\n97\n1,Russ & Ed Sheeran,,,
97,"Bzrp Music Sessions, Vol. 52\nBizarrap & Queve...",Bizarrap & Quevedo,-,94,1
98,Right On\nLil Baby\n97\n13\n15,Lil Baby,,,
99,La Corriente\nBad Bunny & Tony Dize\n99\n32\n9,Bad Bunny & Tony Dize,98,26,7

In [73]:
driver.close()

# 7. Scrape the details of Data science recruiters from naukri.com.

Url = https://www.naukri.com/hr-recruiters-consultants
You have to find the following details:
* A) Name
* B) Designation
* C) Company
* D) Skills they hire for
* E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [74]:
driver=webdriver.Chrome('chromedriver.exe')

driver.maximize_window()
# Getting the webpage of mentioned url 
url=('https://www.naukri.com/')
driver.get(url)
time.sleep(2)

In [75]:
#Fetching urls to navigate recruiter page
recruiter = driver.find_element(By.XPATH,'//a[@title="Search Jobs"]')
page_url = recruiter.get_attribute("href")

driver.get(page_url)
time.sleep(3)

In [76]:
#Fetching urls to navigate recruiter page
recruiter = driver.find_element(By.XPATH,'/html/body/div[1]/div/ul/li[2]/a')
page_url = recruiter.get_attribute("href")

driver.get(page_url)
time.sleep(3)

In [77]:
# Fetching search button, sending keys and clicking on it
search = driver.find_element(By.XPATH,"//div[@class='inpWrap']//input") 
search.send_keys("Data science ")           
btn = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button').click()     
time.sleep(3)

In [78]:
#Creating empty lists
Name = []
Designation = []
Company = []
Skills = []
Location = []

In [79]:
#Scraping data of Names
for i in driver.find_elements(By.XPATH,"//span[@class='fl ellipsis']"):
    Name.append(i.text)
time.sleep(3)

#Scraping data of Designation
for i in driver.find_elements(By.XPATH,"//span[@class='ellipsis clr']"):
    Designation.append(i.text)
    
#Scraping data of company name
for i in driver.find_elements(By.XPATH,"//div[@class='vcard']//p[1]/a[2]"):
    Company.append(i.text)

#Scraping data of locations
for i in driver.find_elements(By.XPATH,"//div[@class='vcard']//p[1]//span"):
    Location.append(i.text)
time.sleep(3)

In [80]:
print(len(Name),len(Designation),len(Company),len(Location))

50 50 50 148

In [81]:
# Creating dataframe for scraped data
Naukri=pd.DataFrame({})
Naukri['Name'] = Name
Naukri['Designation'] = Designation
Naukri['Company'] = Company
Naukri['Location'] = Location[:50]
Naukri

,Name,Designation,Company,Location
0,Aakash Harit,HR Manager,Data Science Network,Aakash Harit
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,HR Manager
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Delhi
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,shravan Kumar Gaddam
4,subhas patel,Founder CEO,LibraryXProject,Company Recruiter
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Hyderabad / Secunderabad
6,Institute for Financial Management and Resear,Programme Manager,IFMR,MARSIAN Technologies LLP
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Company HR
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Pune
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Anik Agrawal
10,Vaishnavi Kudalkar,HR Executive,Codeachive learning,Company Recruiter
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Ahmedabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software,subhas patel
13,Mubarak,Company HR,MoneyTap,Founder CEO
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,UK - (london)
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Abhishek - Only Analytics Hiring - India and
16,Kapil Devang,HR Manager,BISP Solutions,Recruitment Lead Consultant
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Vadodara / Baroda
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Institute for Financial Management and Resear
19,Manisha Yadav,HR Executive,Easi Tax,Programme Manager
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Chennai
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Balu Ramesh
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,HR Administrator
23,Rithika dadwal,HR Recruiter,Affine Analytics,Trivandrum
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Asif Lucknowi
25,Shaun Rao,Manager Human Resources,Exela Technologies,Director
26,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Indore
27,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,InstaFinancials
28,kumar,Proprietor,trainin,Human Resource
29,Sunil Vedula,CEO,Nanoprecise Sci Corp,Bengaluru / Bangalore
30,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Vaishnavi Kudalkar
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,HR Executive
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mumbai
33,Avodha,Business Development Associate,Nikitha Palaparthi,Priyanka Akiri
34,Priya Khare,Senior Manager,Independent Consultant,HR Manager
35,Amit Sharma,Consultant,ASCO consulting,Hyderabad
36,Kanan,senior technology instructor,NY INST,Kalpana Dumpala
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Executive Hiring
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,Hyderabad / Secunderabad
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,Mubarak
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Company HR
41,Ankit Sinha,Head Analytics,Suntech Global,Bengaluru / Bangalore
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Kushal Rastogi
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Company HR
44,Ashwini,Director Global Delivery,MRP Advisers,Mumbai
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Mahesh Babu Channa
46,Rajani Nagaraj,HR Manager,WildJasmine,HR Team Lead
47,ROHIT Kumar,Architect,LNT Private Limited,Hyderabad / Secunderabad
48,Amir Chowdhury,Managing Partner,Granular.ai,Kapil Devang
49,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,HR Manager

In [83]:
driver.close()

# 8. Scrape the details of Highest selling novels.

URL = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare
You have to find the following details:
* A) Book name
* B) Author name
* C) Volumes sold
* D) Publisher
* E) Genre

In [84]:
# connect to webdriver
driver = webdriver.Chrome("chromedriver.exe")

# get webpage
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

In [85]:
#Creating empty list
Bookname = []
Authorname = []
Volumessold = []
Publisher = []
Genre = []

In [86]:
#scraping book names data
for i in driver.find_elements(By.XPATH,"//tbody//tr/td[2]"):
    Bookname.append(i.text)
    
#Scraping author names data
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[3]"):
    try:
        if i.text == '0' : raise NoSuchElementException
        Authorname.append(i.text)
    except NoSuchElementException:
        Authorname.append('-')
time.sleep(1)

#Scraping data of volumes sold
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[4]"):
    Volumessold.append(i.text)
    
#Scraping data of publisher names
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[5]"):
    Publisher.append(i.text)
    
#Scraping data of genre
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[6]"):
    Genre.append(i.text)

In [87]:
#Creating dataframe for scraped data
Novels=pd.DataFrame({})
Novels['Book Name'] = Bookname
Novels['Author'] = Authorname
Novels['Volume sold'] = Volumessold
Novels['Publisher'] = Publisher
Novels['Genre'] = Genre
Novels

,Book Name,Author,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [88]:
driver.close()

# 9. Scrape the details most watched tv series of all time from imdb.com.

Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:

* A) Name
* B) Year span
* C) Genre
* D) Run time
* E) Ratings
* F) Votes

In [89]:
# connect to webdriver
driver = webdriver.Chrome("chromedriver.exe")
# get webpage
driver.get("https://www.imdb.com/list/ls095964455/")
driver.maximize_window()

In [90]:
#Creating empty lists.
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

#Scraping data of Names
for i in driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/a"):
    Name.append(i.text)
    
#Scraping data of Year span
for i in driver.find_elements(By.XPATH,"//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)
    
#Scraping data of Run time
for i in driver.find_elements(By.XPATH,"//span[@class='runtime']"):
    Run_time.append(i.text)
    
#Scraping data of Ratings
for i in driver.find_elements(By.XPATH,"//div[@class='ipl-rating-star small']//span[2]"):
    Ratings.append(i.text)
    
#Scraping data of genre
for i in driver.find_elements(By.XPATH,"//span[@class='genre']"):
    Genre.append(i.text)
    
#Scraping data of votes
for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text)

In [91]:
# Creating dataframe for scraped data
TVseries=pd.DataFrame({})
TVseries['Name'] = Name
TVseries['Year Span'] = Year_span
TVseries['Genre'] = Genre
TVseries['Run Time'] = Run_time
TVseries['Ratings'] = Ratings
TVseries['Votes'] = Votes
TVseries

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,020,382"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,116,077"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"959,364"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"286,819"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"246,406"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"49,259"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"60,132"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"193,349"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,798"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"233,179"

In [92]:
driver.close()

# 10. Details of Datasets from UCI machine learning repositories.

Url = https://archive.ics.uci.edu/
You have to find the following details:

* A) Dataset name
* B) Data type
* C) Task
* D) Attribute type
* E) No of instances
* F) No of attribute
* G) Year

Note: - from the home page you have to go to the ShowAllDataset page through code.

In [93]:
# connect to webdriver
driver = webdriver.Chrome("chromedriver.exe")
# get webpage
driver.get(" https://archive.ics.uci.edu/")
driver.maximize_window()

In [94]:
# Finding view all dataset button from the webpage
viewall_dataset = driver.find_element(By.XPATH,"//tbody[1]//tr/td[2]/span[2]/a")    
page_url = viewall_dataset.get_attribute("href")
driver.get(page_url)

In [95]:
# Fetching page urls of all datasets 
view_list = driver.find_element(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a")  
list_url = view_list.get_attribute("href")           
driver.get(list_url)

In [96]:
# Fetching urls for each dataset
dataset_url = driver.find_elements(By.XPATH,"//p[@class='normal']//b/a")    

urls = []     
for i in dataset_url:
    urls.append(i.get_attribute("href"))

In [97]:
#Creating empty lists
Dataset_name = []
Data_type = []
Task = []
Attribute_type = []
No_of_instances = []
No_of_attributes = []
Year = []

In [99]:
for i in urls:
    driver.get(i)
    time.sleep(2)
    
    #Scraping Dataset name
    try: 
        dataset_name = driver.find_element(By.XPATH,"//span[@class='heading']")
        Dataset_name.append(dataset_name.text)
    except NoSuchElementException:
        Dataset_name.append('-')
    
    
    #Scraping data type
    try:
        data_type = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr/td[2]")
        if data_type.text == "N/A": raise NoSuchElementException
        Data_type.append(data_type.text)
    except NoSuchElementException:
        Data_type.append('-')
    
    
    #scraping Task
    try:
        task = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[3]/td[2]")
        if task.text == "N/A": raise NoSuchElementException
        Task.append(task.text)
    except NoSuchElementException:
        Task.append('-')
    
    
    # Scraping Attribute type
    try:
        attribute_type = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[2]")
        if attribute_type.text == "N/A": raise NoSuchElementException
        Attribute_type.append(attribute_type.text)
    except NoSuchElementException:
        Attribute_type.append('-')
    
    
    # Scraping No of instances
    try:
        instances = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr/td[4]")
        if instances.text == "N/A": raise NoSuchElementException
        No_of_instances.append(instances.text)
    except NoSuchElementException:
        No_of_instances.append('-')
    
    
    # Scraping No of attributes
    try:
        attribute = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[4]")
        if attribute.text == "N/A": raise NoSuchElementException
        No_of_attributes.append(attribute.text)
    except NoSuchElementException:
        No_of_attributes.append('-')
    
    
    # Scraping year
    try:
        year = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[6]")
        if year.text == "N/A": raise NoSuchElementException
        Year.append(year.text[:4])
    except NoSuchElementException:
        Year.append('-')

In [101]:
# Creating dataframe 

ML=pd.DataFrame({})
ML['Data Name'] = Dataset_name[:622]
ML['Data Type'] = Data_type[:622]
ML['Task'] = Task[:622]
ML['Attribute type'] = Attribute_type[:622]
ML['No of instance'] = No_of_instances[:622]
ML['No of attributes'] = No_of_attributes[:622]
ML['Year'] = Year[:622]
ML

,Data Name,Data Type,Task,Attribute type,No of instance,No of attributes,Year
0,2.4 GHZ Indoor Channel Measurements Data Set,Multivariate,Classification,Real,7840,5,2018
1,"3D Road Network (North Jutland, Denmark) Data Set","Sequential, Text","Regression, Clustering",Real,434874,4,2013
2,3W dataset Data Set,"Multivariate, Time-Series","Classification, Clustering","Integer, Real",1984,8,2019
3,9mers from cullpdb Data Set,Sequential,"Classification, Regression",Real,158716,4,2021
4,: Simulated Data set of Iraqi tourism places D...,Multivariate,"Classification, Clustering",-,232,16,2020
...,...,...,...,...,...,...,...
617,Reuter_50_50 Data Set,"Multivariate, Text, Domain-Theory","Classification, Clustering",Real,2500,10000,2011
618,REWEMA Data Set,Multivariate,Classification,Integer,6272,632,2020
619,Rice (Cammeo and Osmancik) Data Set,Multivariate,Classification,Real,3810,8,2019
620,Rice Leaf Diseases Data Set,Multivariate,Classification,Integer,120,-,2019
621,Risk Factor prediction of Chronic Kidney Disea...,Multivariate,"Classification, Regression",Real,202,29,2021

In [102]:
driver.close()